vim.cmd('source $HOME/.config/nvim/vim/init.vim')

require('plugins/bufferline')
require('plugins/nvimtree')
require('plugins/lualine')
require('plugins/neoscroll')
require('plugins/treesitter')
require('plugins/nvim-cmp')
require('plugins/luasnip')
require('plugins/tabnine')
require('plugins/lsp')
require('plugins/telescope')
require'colorizer'.setup()
require('plugins/dashboard')
